In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
main_df=pd.DataFrame(columns=['adsorbent', 'adsorbates', 'temperature(k)', 'pressure', 'pressureUnits', 'total_adsorption', 'adsorptionUnits', 'DOI'])
main_df

Empty DataFrame
Columns: [adsorbent, adsorbates, temperature(k), pressure, pressureUnits, total_adsorption, adsorptionUnits, DOI]
Index: []

In [3]:
path = 'E:/Python Projects/shohreh/Shohreh_GitHub_Repository/NISTARPA-E Database/Zeolite-CO2 Data/Data/'

In [4]:
'''
command script in the Data folder: dir > documents_list.txt
Make input_path with direction of your Data folder
then Run this code
'''
import re

input_path = 'E:/Python Projects/shohreh/Shohreh_GitHub_Repository/NISTARPA-E Database/Zeolite-CO2 Data/documents_list.txt'

Item_list = []

with open(input_path, 'r', encoding = 'utf-16') as f:
    lines = f.readlines()
    for line in lines:
        match= re.search(r'\d{2}\.\d{4}[^\s]+\.csv', line)
        if match:
            item = match.group()
            Item_list.append(item)
        else:
            continue

In [5]:
def extract_basicInfo(dataframe):
    columns=['temperature', 'pressureUnits', 'adsorptionUnits', 'DOI']
    instant_values=[]
    for col in columns:
        for index, row in dataframe.iterrows():
            # Check if the row contains col information
            if col in str(row.values):
                col = (row.str.split(','))[0][1]
                value=col.strip('"')
                instant_values.append(col.strip('"'))
    return instant_values

In [6]:
# Function to search for adsorbent in all rows
def extract_adsorbent_adsorbates(df):
    for i, row in df.iterrows():
        # Check if the row contains adsorbent information
        if 'adsorbent' in str(row.values):
            adsorbent= (df.iloc[i+2]).str.split(',')[0][1]
            Adsorbent= adsorbent.strip('"') # Remove quotes if present
        if 'adsorbates' in str(row.values):
            adsorbates= (df.iloc[i+2]).str.split(',')[0][1]
            Adsorbates= adsorbates.strip('"') # Remove quotes if present       
           
    return [Adsorbent,Adsorbates]

In [7]:
def extract_pressure_adsoption(dataframe,variable,unit):
    values_list=[]
    for i, row in dataframe.iterrows():
        # Check if the row contains value information
        if variable in str(row.values):
            list=(row.str.split(',')[0][1]).strip('" ')
            list=list.replace(unit, '').replace(variable, '').strip()
            try:
                numeric_list= float(list)
                values_list.append(numeric_list)
            except ValueError:
                continue
    return values_list

In [8]:
def extract_data(path):
    df = pd.read_csv(path, delimiter='\t')
    instant_values = extract_basicInfo(df)
    adsorbent= extract_adsorbent_adsorbates(df)[0]
    adsorbates= extract_adsorbent_adsorbates(df)[1]
    pressure_values = extract_pressure_adsoption(df,'pressure', 'bar')
    adsorption_values = extract_pressure_adsoption(df,'pressure', 'bar')

    loop_df= pd.DataFrame(np.nan,
                          index=range(len(adsorption_values)),
                          columns=['adsorbent', 'adsorbates', 'temperature(k)', 'pressure', 'pressureUnits', 'total_adsorption', 'adsorptionUnits', 'DOI']
                         )
    loop_df['adsorbent'] = adsorbent
    loop_df['adsorbates'] = adsorbates
    loop_df['temperature(k)'] = instant_values[0]
    loop_df['pressure'] =  pressure_values
    loop_df['pressureUnits'] = instant_values[1]
    loop_df['total_adsorption'] = adsorption_values
    loop_df['adsorptionUnits'] = instant_values[2]
    loop_df['DOI'] = instant_values[3]
    return loop_df

In [33]:
for item in Item_list:
    df= extract_data(path+item)
    main_df = pd.concat([main_df, df], ignore_index=True)
main_df

,adsorbent,adsorbates,temperature(k),pressure,pressureUnits,total_adsorption,adsorptionUnits,DOI
0,Zeolite LS-Li-KFI,Carbon Dioxide,303,0.235795,bar,0.235795,mmol/g,10.1021/La400352r
1,Zeolite LS-Li-KFI,Carbon Dioxide,303,0.516862,bar,0.516862,mmol/g,10.1021/La400352r
2,Zeolite LS-Li-KFI,Carbon Dioxide,303,1.221770,bar,1.221770,mmol/g,10.1021/La400352r
3,Zeolite LS-Li-KFI,Carbon Dioxide,303,2.844770,bar,2.844770,mmol/g,10.1021/La400352r
4,Zeolite LS-Li-KFI,Carbon Dioxide,303,6.826760,bar,6.826760,mmol/g,10.1021/La400352r
...,...,...,...,...,...,...,...,...
11434,Zeolite LS-Li-KFI,Carbon Dioxide,303,2.844770,bar,2.844770,mmol/g,10.1021/La400352r
11435,Zeolite LS-Li-KFI,Carbon Dioxide,303,6.826760,bar,6.826760,mmol/g,10.1021/La400352r
11436,Zeolite LS-Li-KFI,Carbon Dioxide,303,16.382600,bar,16.382600,mmol/g,10.1021/La400352r
11437,Zeolite LS-Li-KFI,Carbon Dioxide,303,34.320900,bar,34.320900,mmol/g,10.1021/La400352r
11438,Zeolite LS-Li-KFI,Carbon Dioxide,303,43.040600,bar,43.040600,mmol/g,10.1021/La400352r

In [34]:
main_df.to_csv('Data.csv',index=False)